### PR TITLE
Modified message for completed kills

### PR DESCRIPTION
**Pull request by aeskathon**
No point in showing target for journal if user already has the achievement.
It's just easier to see whether you have killed enough if the message is different. And you can still see the number of kills for grinding purposes.

### CODE REVIEW

**Comment by TehSeph** [comment]
I believe Excrulon was originally planning to just disable the popup entirely after kill count had been achieved. This is a nice placeholder until then though. :+1:

**Comment by aeskathon** [comment]
It could be useful to see how many mobs you have killed if you are grinding for a rare collection item.

**Comment by Excrulon** [comment]
There is an option in the lua for not showing the notice if complete.

showNoticeIfComplete = true;

And I disagree anyway, I always like seeing my kill counts and total, even if complete. It can just be another option.

**Comment by aeskathon** [comment]
Ok, I'll try to expand why I made this change.
You can farm the mobs one day, make enough kills of mob#1 and not enough of mob#2.
Next day (or couple of days later) you return to your genocide job having completely forgotten, which type do you need to kill more.
You can check the journal of course, but I think everyone will agree that it is difficult to use. There are hundrends if not thousands of mobs and you have to input their names to find them.
So you can kill a mob and look at the numbers. With this change you clearly see that you have killed enough of them. Without it you have to compare the two numbers. It is not hard of course, but if it can be made easier, why not do it? Addons are always about convenience.

If you don't want to have different messages, maybe do them in different color?

Not displaying a message is bad because you don't know if you killed enough or you are not required to kill them, or there's a glitch and it's not displayed because of that (sometimes you have to kill several mobs before it starts showing).

**Pull request closed without merging**
